version: '0.2'
words:
  - Uranos
  - Aither
  - Hemera
  - ROLLBAR
  - starten
  - codacy
  - pylint
  - xzfv
  - swiftlang
  - cocoalumberjack
  - Laparo
  - Thalassa
  - Andreas
  - Bernt
  - Baertl
  - Lege
  - neue
  - Anforderungen
  - unter
  - Erzeuge
  - bevor
  - geändert
  - wird
  - Halte
  - Implementierungen
  - validiere
  - Nutze
  - primäre
  - Entwicklungsumgebung
  - Schreibe
  - halte
  - konsistent
  - produktive
  - Quellen
  - spezifische
  - Erweiterungen
  - Referenz
